import type { Quest, Badge } from "../types";

export const MOCK_QUESTS: Quest[] = [
  {
    id: "q1",
    emoji: "🌸",
    title: "近所で桜を1枚撮る",
    oneLiner: "玄関から100歩以内で見つけよう",
    steps: ["玄関を出る", "桜を見つける", "1枚だけ撮る"],
    minutes: 5,
    cost: 0,
    difficulty: "easy",
    tags: ["散歩", "自然", "5分"],
    color: "pink",
    doneCount: 142,
  },
  {
    id: "q2",
    emoji: "☕️",
    title: "新しいカフェに入ってみる",
    oneLiner: "通り過ぎてた場所に勇気を出して",
    steps: ["気になってた店をひとつ思い出す", "扉を開ける", "1杯だけ頼む"],
    minutes: 30,
    cost: 600,
    difficulty: "easy",
    tags: ["食", "発見"],
    color: "yellow",
    doneCount: 89,
  },
  {
    id: "q3",
    emoji: "📚",
    title: "本屋で気になる1冊を立ち読み",
    oneLiner: "買わなくていい、3ページだけ",
    steps: ["本屋に入る", "ジャケ買いしそうな1冊を選ぶ", "3ページ読む"],
    minutes: 10,
    cost: 0,
    difficulty: "easy",
    tags: ["読書", "発見", "10分"],
    color: "blue",
    doneCount: 213,
  },
  {
    id: "q4",
    emoji: "🌅",
    title: "朝6時の空を見る",
    oneLiner: "ベランダでも、窓からでもいい",
    steps: ["アラームを6時にセット", "起きる", "空を1分だけ眺める"],
    minutes: 3,
    cost: 0,
    difficulty: "normal",
    tags: ["朝", "自然"],
    color: "purple",
    doneCount: 56,
  },
  {
    id: "q5",
    emoji: "🍜",
    title: "知らないラーメン屋に入る",
    oneLiner: "1番人気を頼むだけ",
    steps: ["地図で☆4以上を探す", "並んでいたら諦めて次", "1番人気を注文"],
    minutes: 30,
    cost: 1000,
    difficulty: "normal",
    tags: ["食", "冒険"],
    color: "orange",
    doneCount: 178,
  },
  {
    id: "q6",
    emoji: "✏️",
    title: "今日の気分を3行で書く",
    oneLiner: "誰にも見せない日記",
    steps: ["紙とペンを用意", "今日の気分を3行で", "閉じる"],
    minutes: 5,
    cost: 0,
    difficulty: "easy",
    tags: ["創作", "ひとり時間", "5分"],
    color: "green",
    doneCount: 312,
  },
  {
    id: "q7",
    emoji: "🚶",
    title: "いつもと違う道で帰る",
    oneLiner: "1本ずれるだけで世界が変わる",
    steps: ["駅を出る", "いつもの逆を選ぶ", "迷ったら地図"],
    minutes: 15,
    cost: 0,
    difficulty: "easy",
    tags: ["散歩", "発見"],
    color: "blue",
    doneCount: 421,
  },
  {
    id: "q8",
    emoji: "🎨",
    title: "5分で何かを描く",
    oneLiner: "うまさは気にしない、線だけでいい",
    steps: ["紙とペンを用意", "目の前の何かを5分で", "保存しなくてOK"],
    minutes: 5,
    cost: 0,
    difficulty: "easy",
    tags: ["創作", "5分"],
    color: "pink",
    doneCount: 67,
  },
];

export const MOCK_BADGES: Badge[] = [
  { id: "b1", emoji: "🌸", name: "春のはじめ", description: "春に1回やった", unlocked: true },
  { id: "b2", emoji: "🌅", name: "朝活デビュー", description: "6-9時にやった", unlocked: true },
  { id: "b3", emoji: "🚶", name: "散歩マスター", description: "#散歩 を10回", unlocked: true },
  { id: "b4", emoji: "☕️", name: "カフェ巡り", description: "#食 を5回", unlocked: true },
  { id: "b5", emoji: "✏️", name: "創作の芽", description: "#創作 を3回", unlocked: true },
  { id: "b6", emoji: "🌊", name: "夏の足跡", description: "夏に1回", unlocked: false },
  { id: "b7", emoji: "🍂", name: "秋の発見", description: "秋に1回", unlocked: false },
  { id: "b8", emoji: "❄️", name: "冬のひとり", description: "冬に1回", unlocked: false },
  { id: "b9", emoji: "🌙", name: "夜更かし", description: "22時以降にやった", unlocked: false },
  { id: "b10", emoji: "🔥", name: "3連続", description: "3日連続", unlocked: false },
];

export const MOCK_RECENT_PHOTOS = [
  "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1457089328389-f5a734ce2cea?w=200&h=200&fit=crop",
];
